### ISSUE TITLE
New HTTP/s authentications

### ISSUE THREAD

**Issue by virgs** [enqueuer-land/enqueuer#15]
Bearer
Digest
NTLM
OAuth 1.0
OAuth 2.0
Hawk
AWS signature

**Comment by lopidio** [comment]
God bless you, @rodrigorech

**Comment by lopidio** [comment]
- [x] Basic
 - [x] Bearer
 - [x] Digest
 - [ ] NTLM
 - [ ] OAuth 1.0
 - [ ] OAuth 2.0
 - [ ] Hawk
 - [ ] AWS signature
