### ISSUE TITLE
Tests appear to be counted twice

### ISSUE THREAD

**Issue by akhilesh-bangalore** [enqueuer-land/enqueuer#65]
**Describe the bug**
On the summary displayed following a run, the count is twice the number of actual tests.

**To Reproduce**
1. Create `test.yml` file with a publisher defined as
```publishers:
-   name: Sample
    type: http
    url: https://www.google.co.in
    onResponseReceived:
      assertions:
      -   expect: statusCode
          toBeEqualTo: 200
```
2. execute `nqr test.yml`
3. See error
```[2020-06-05T19:23:31.307Z] [INFO] - Rocking and rolling
           [PASS]      test.yml                                                           2      tests passing of 2      (100%) | executed in 271ms
   ----------------
           [PASS] enqueuer                                                                2      tests passing of 2      (100%) | executed in 278ms
[2020-06-05T19:23:32.001Z] [INFO] - Hope you had a great time
```
Even though there is only one test, the count shows 2.

**Expected behavior**
```[2020-06-05T19:23:31.307Z] [INFO] - Rocking and rolling
           [PASS]      test.yml                                                           1      tests passing of 1      (100%) | executed in 271ms
   ----------------
           [PASS] enqueuer                                                                1      tests passing of 1      (100%) | executed in 278ms
[2020-06-05T19:23:32.001Z] [INFO] - Hope you had a great time
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by virgs** [comment]
Thanks for the report.
But I think it's an expected behavior, though.
```
➜  git:(master) ✗ nqr test.yml -m 3
[2020-06-05T19:42:17.829Z] [INFO] - Rocking and rolling
           [PASS]      test.yml                                                           2      tests passing of 2      (100%) | executed in 284ms
           [PASS]            Sample                                                       2      tests passing of 2      (100%)
           [NULL]                  onInit                                                 0      tests passing of 0      (100%)
           [PASS]                  onFinish                                               1      tests passing of 1      (100%)
           [PASS]                  onResponseReceived                                     1      tests passing of 1      (100%)
           [NULL]                  onMessageReceived                                      0      tests passing of 0      (100%)
           [NULL]            onInit                                                       0      tests passing of 0      (100%)
           [NULL]            onFinish                                                     0      tests passing of 0      (100%)
   ----------------
           [PASS] enqueuer                                                                2      tests passing of 2      (100%) | executed in 290ms
[2020-06-05T19:42:18.495Z] [INFO] - Hope you had a great time
```

If you run `nqr test.yml -m 3` (or scroll right the snippet above) you'll identify this "extra" test is auto generated by every publisher, as said in the docs: 

> 2.2 Publisher
> ... It's worth noting that it always creates a message. That's the reason why there's an implicitly created test in `onFinish` hook verifying if the message got published.

In your scenario, this test verifies if the url `https://www.google.co.in` is reachable.

Hope I got your question answered.

**Comment by akhilesh-bangalore** [comment]
Thanks for the response.

It clarifies the behaviour. However, the incorrect count skews the test stats. Is there a way to get the correct count?

**Comment by virgs** [comment]
I'm not sure I get your point.
The correct value is 2 indeed. The assertion you created and the default one.

There's no way to disable the default one, if that's what you're asking for. 😞

**Comment by akhilesh-bangalore** [comment]
Yes, I was asking if there was a way to disable the default one.

Well, I agree that the count is infact 2 due to the implicit/default assertion. I also understand that this is by design, however, since the default assertion not included in the script/test itself it gives a wrong impression upon seeing the final message.

Anyhow, thanks for the confirmation. Appreciate it.

**Comment by virgs** [comment]
Sorry for taking so long to reply, I was thinking about it.

So, I don't think it's a good idea to create an option to disable the default/implicit tests. It could lead to the wrong feeling that everything is OK even though the subscription didn't receive any message and the publisher was not able to do anything.
What I can do, instead, is to create an option to show, beyond the default stats, the explicitly declared one.
Something like:

`[PASS] enqueuer                                                                2      tests passing of 2 (100%) | executed in 290ms (0/0 of explicitly declared)`

Does it solve your issue?
Let me know if you have any suggestion.

Thanks.

**Comment by akhilesh-bangalore** [comment]
Sorry about the delayed response.

> So, I don't think it's a good idea to create an option to disable the default/implicit tests. It could lead to the wrong feeling that everything is OK even though the subscription didn't receive any message and the publisher was not able to do anything.

Yes that is a possibility. However, if such a situation does arise, it is very likely that the specific assertions included on the test to fail. Having said that, I can see where you are coming from and an option to filter out the noise from implicit tests should be sufficient. The messaging seems to give enough relevant details.

Thanks,

**Comment by virgs** [comment]
@akhilesh-bangalore Checkout [this PR](https://github.com/enqueuer-land/enqueuer/pull/68) and let me know if it works for you.

**Comment by akhilesh-bangalore** [comment]
The modification seems to spit out the count of implicit tests as opposed to showing the count of explicit ones as decribed [above](https://github.com/enqueuer-land/enqueuer/issues/65#issuecomment-651766392)

Output: 
```
C:\>nqr -d test.yml
[2020-07-14T15:17:03.063Z] [INFO] - Rocking and rolling
           [PASS]      test.yml                                                           2      tests passing of 2      (100%) | executed in 711ms     | (1/1 of implicitly declared)
   ----------------
           [PASS] enqueuer                                                                2      tests passing of 2      (100%) | executed in 714ms     | (1/1 of implicitly declared)
[2020-07-14T15:17:04.251Z] [INFO] - Hope you had a great time
```

**Comment by virgs** [comment]
Hmm. Sure, I'll invert that and upload a new version. Does it sound good?

**Comment by akhilesh-bangalore** [comment]
This looks good. Appreaciate it.  👍
